# Model color schemes
model_colors:
  N-BEATS: '#ff7f0e'  # Orange
  Prophet: '#2ca02c'  # Green
  TiDE: '#d62728'     # Red
  TSMixer: '#9467bd'  # Purple
  Chronos: '#8c564b'  # Brown

# Line styles for different data types
line_styles:
  historical:
    color: '#1f77b4'  # Blue
    width: 2
  training:
    color: '#2ca02c'  # Green
    width: 2
  test:
    color: '#17becf'  # Light blue
    width: 2
  forecast:
    dash: 'dash'
    width: 1.5
  backtest:
    dash: 'dot'
    width: 1.5

# Plot layout configuration
plot_layout:
  template: 'plotly_dark'
  showlegend: true
  legend:
    yanchor: "top"
    y: 0.99
    xanchor: "left"
    x: 0.01
    bgcolor: "rgba(0,0,0,0.5)"
  hovermode: 'x unified'
  height: 600
  margin:
    l: 50
    r: 50
    t: 50
    b: 50

# Metrics table styling
metrics_table_style:
  background-color: 'rgba(47, 47, 47, 0.8)'
  color: 'white'
  border: '1px solid gray'
