---
name: CI

on:
  push:
    branches: ["main", "feature/**"]
  pull_request:
    branches: ["main"]

jobs:
  lint-format-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install CI dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .github/workflows/ci-requirements.txt

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Install Prettier
        run: npm install -g prettier prettier-plugin-yaml

      - name: Format YAML files with Prettier
        run: prettier --write "**/*.{yml,yaml}"

      - name: Lint and format code with Ruff
        run: |
          ruff format .
          ruff check . --fix

      - name: Lint code with Flake8
        run: flake8 .

      - name: Lint YAML files with Yamllint
        run: yamllint -c .yamllint .

  build-docker-image:
    needs: lint-format-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: myapp:${{ github.sha }}
