name: CI

on:
  push:
    branches:
      - main
      - "feature/**"
  pull_request:
    branches:
      - main

jobs:
  lint-format-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install CI dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .github/workflows/ci-requirements.txt

      - name: Format code with Ruff
        run: |
          ruff check . --fix

      - name: Lint code with Flake8
        run: |
          flake8 .

      - name: Lint YAML files with Yamllint
        run: |
          yamllint .

    #   - name: Run tests with Pytest
    #    run: |
    #     pytest
