name: Frontend CI

on:
  push:
    branches: ["main", "feature/**"]
    paths:
      - "**/*.ts"
      - "**/*.tsx"
      - "**/*.css"
      - "**/*.html"
      - "**/*.yaml"
      - "**/*.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "**/*.ts"
      - "**/*.tsx"
      - "**/*.css"
      - "**/*.html"
      - "**/*.yaml"
      - "**/*.yml"

jobs:
  lint-format-test:
    name: Lint, Format, and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install frontend dependencies
        run: npm install

      - name: Run frontend tests
        run: npm test -- --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true

      - name: Install Prettier
        run: npm install

      - name: Format YAML files with Prettier
        run: npx prettier --write "**/*.yaml"
