name: Frontend CI

on:
  push:
    branches: ["main", "feature/**"]
    paths:
      - "**/*.ts"
      - "**/*.tsx"
      - "**/*.css"
      - "**/*.html"
      - "**/*.yaml"
      - "**/*.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "**/*.ts"
      - "**/*.tsx"
      - "**/*.css"
      - "**/*.html"
      - "**/*.yaml"
      - "**/*.yml"

jobs:
  lint-format-test:
    name: Lint, Format, and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Cache pnpm store
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install frontend dependencies
        run: pnpm install

      - name: Run frontend tests
        run: pnpm test -- --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true

      - name: Install Prettier
        run: pnpm add --save-dev prettier --ignore-scripts

      - name: Format YAML files with Prettier
        run: pnpx prettier --write "**/*.yaml"
