---
name: Frontend CI

"on":
  push:
    branches: [main, feature/**]
    paths:
      - "**/*.ts"
      - "**/*.tsx"
      - "**/*.css"
      - "**/*.html"
      - "**/*.yaml"
      - "**/*.yml"
      - "frontend/package.json"
      - "frontend/pnpm-lock.yaml"
  pull_request:
    branches: [main]
    paths:
      - "**/*.ts"
      - "**/*.tsx"
      - "**/*.css"
      - "**/*.html"
      - "**/*.yaml"
      - "**/*.yml"
      - "frontend/package.json"
      - "frontend/pnpm-lock.yaml"

jobs:
  lint-format-test:
    name: Lint, Format, and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: pnpm install --frozen-lockfile

      - name: Lint frontend code
        working-directory: ./frontend
        run: pnpm lint

      - name: Run frontend tests
        working-directory: ./frontend
        run: pnpm test -- --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./frontend/coverage/lcov.info
          flags: frontend
          name: codecov-frontend
          fail_ci_if_error: true

      - name: Format code
        working-directory: ./frontend
        run: pnpm format:check
